### ISSUE TITLE
Togliete il sito dalla sottocartella

### ISSUE THREAD

**Issue by tmontanaro** [SoNet-2017/Arte#1]
Togliete il sito dalla sottocartella seguendo queste istruzioni:
a) chiudere (se e' aperto) webstorm
b) andare nella cartella in cui e' stato salvato il progetto (es.
C:/Users/Teo/Desktop/progetto)
c) entrare nella sottocartella (nel repository d'esempio, entrare
quindi in C:/Users/Teo/Desktop/progetto/sottocartella)
d) tagliare tutto il contenuto e incollarlo nella cartella padre
(C:/Users/Teo/Desktop/progetto)
e) eliminare la sottocartella
f) riaprire webstorm
g) cliccare su VCS (dai menu in alto), Git, Commit Directory
h) Inserire un commento per il commit e poi premere "Commit" e "Commit
and Push"

PS. Non ve l'ho spiegato, ma in github esistono le "Issue"! Si tratta di un modo per tenere traccia dei problemi! Questa qui in cui sto scrivendo è una issue! Se andate sul repository, e cliccate su "Issues" la trovate tra quelle ancora non risolte. Quando avrete risolto, quindi, cliccateci su e poi premete il tasto "chiudi issue"!

**Comment by gare93** [comment]
Done
